# Default values for ueransim-ue.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
global:
  imageRegistry: ""
  ## E.g.
  ## imagePullSecrets:
  ##   - myRegistryKeySecretName
  ##
  imagePullSecrets: []
  storageClass: ""

## Repositorio de docker
image:
  registry: docker.io
  repository: agustinvl/gira
  tag: ueransim
  pullPolicy: Always
  pullSecrets: []
  debug: false
  # Overrides the image tag whose default is the chart appVersion.

## Nombre
name: ueransim-gnb
enabled: true
## Configuraciones ##
## Direccion IP del gNodeB al UE
ipLink: 127.0.0.1
# Dirección hacia el core
ipCore: 127.0.0.2
# Dirección del AMF
ipAMF: 127.0.0.5
# Información interna del gNodeB
# Mobile Country Code (MCC)
mcc: '999'
# Mobile Network Code (MNC)
mnc: '70'
# NR Cell identity (Hexadecimal)
nci: '0x000000010'
# Tracking Area Code (TAC)
tac: 1
# Service/Slice Type (SST)
sst: 1
# Slice Diferentiator (SD)
sd: 1
## Configuración del servicio ##
service:
  ue:
    port: 4433
  core:
    port: 3344
# Configuraciones para la asignacion de recursos
resources:
  limits: {}
  requests: {}
# Configuración para la asignación de nodo para el despliegue
# nodeSelector: {}
