apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "srs-gnb.fullname" . }}-configmap
  namespace: {{.Release.Namespace | quote}}
data:
  gnb.yaml: |
{{ tpl (.Files.Get "resources/gnb.yaml") . | indent 4 }}