apiVersion: v1
kind: Service
metadata:
  name: {{ include "srs-gnb.fullname" . }}
  labels:
    {{- include "srs-gnb.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: gnb-ue
      port: 2000
      protocol: TCP
    - name: gnb-core
      port: {{ .Values.service.core.port}}
      protocol:  TCP
    - name: mgm-connection
      port: 22
      protocol: TCP
  publishNotReadyAddresses: true
  selector:
    {{- include "srs-gnb.selectorLabels" . | nindent 4 }}