apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "srs-enb.fullname" . }}-configmap
  namespace: {{.Release.Namespace | quote}}
data:
  enb.conf: |
{{ tpl (.Files.Get "resources/enb.conf") . | indent 4 }}
  rr.conf: |
{{ tpl (.Files.Get "resources/rr.conf") . | indent 4 }}