apiVersion: v1
kind: Service
metadata:
  name: {{ include "ueransim-ue.fullname" . }}
  labels:
    {{- include "ueransim-ue.labels" . | nindent 4 }}
spec:
  clusterIP: None
  ports:
    - name: gnb-ue
      port: {{ .Values.service.port}}
      protocol: UDP
    - name: mgm-connection
      port: 22
      protocol: TCP
  publishNotReadyAddresses: true
  selector:
    {{- include "ueransim-ue.selectorLabels" . | nindent 4 }}
