apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ueransim-ue.fullname" . }}-configmap
  namespace: {{.Release.Namespace | quote}}
data:
  ue.yaml: |
{{ tpl (.Files.Get "resources/ue.yaml") . | indent 4 }}