# IMSI number of the UE. IMSI = [MCC|MNC|MSISDN] (In total 15 digits)
supi: 'imsi-{{ .Values.mcc }}{{ .Values.mnc }}{{ .Values.initialMSISDN }}'
# Mobile Country Code value of HPLMN
mcc: '{{ .Values.mcc}}'
# Mobile Network Code value of HPLMN (2 or 3 digits)
mnc: '{{ .Values.mnc}}'
# Permanent subscription key
key: '{{ .Values.key}}'
# Operator code (OP or OPC) of the UE
op: '{{ .Values.op}}'
# This value specifies the OP type and it can be either 'OP' or 'OPC'
opType: '{{ .Values.optype}}'
# Authentication Management Field (AMF) value
amf: '8000'
# IMEI number of the device. It is used if no SUPI is provided
imei: '{{ .Values.imei}}'
# IMEISV number of the device. It is used if no SUPI and IMEI is provided
imeiSv: '{{ .Values.imeiSv}}'
# List of gNB IP addresses for Radio Link Simulation
gnbSearchList:
  - {{ .Values.gnb_ip}}
# UAC Access Identities Configuration
uacAic:
  mps: false
  mcs: false
# UAC Access Control Class
uacAcc:
  normalClass: 0
  class11: false
  class12: false
  class13: false
  class14: false
  class15: false

# Initial PDU sessions to be established
sessions:
  {{- range .Values.apnList }}
  - {{- toYaml . | nindent 4 }}
  {{- end }}

# Configured NSSAI for this UE by HPLMN
configured-nssai:
  - sst: {{ .Values.sst}}

# Default Configured NSSAI for this UE
default-nssai:
  - sst: {{ .Values.sst}}
    sd: {{ .Values.sd}}

# Supported integrity algorithms by this UE
integrity:
  IA1: true
  IA2: true
  IA3: true

# Supported encryption algorithms by this UE
ciphering:
  EA1: true
  EA2: true
  EA3: true

# Integrity protection maximum data rate for user plane
integrityMaxRate:
  uplink: 'full'
  downlink: 'full'
