apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "srs-ue.fullname" . }}-configmap
  namespace: {{.Release.Namespace | quote}}
data:
  ue.conf: |
{{ tpl (.Files.Get "resources/ue.conf") . | indent 4 }}